### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Akshita-1997** [thomaswang/react-native-gradient-buttons#24]
`@unimodules/core` from `node_modules/expo-haptics/build/Haptics.js

**Comment by maoapp** [comment]
did you get solved it ? @Akshita-1997

**Comment by allens01** [comment]
I think this [PR](https://github.com/thomaswang/react-native-gradient-buttons/pull/23) resolves it

**Comment by thomaswang** [comment]
Hey! Please see https://github.com/thomaswang/react-native-gradient-buttons#requirements for using this in a pure React Native project.

https://github.com/expo/expo/tree/master/packages/react-native-unimodules

```
npm install react-native-unimodules
```
